pool:
  name: TEST

steps:
- task: MSBuild@1
  inputs:
    solution: 'AnyStore.sln'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'